### ISSUE TITLE
OPtimization of modernizr

### ISSUE THREAD

**Issue by jelo77** [ubc-web-services/Megatron#28]
Google Webmaster tools complains about the integration of modernizr. Apparently, it does not get compressed, but compressing the file could save 57%. It doesn't get minified either while all other JS libraries have a minified version.

Another complaint is that it is render-blocking which might be by design if modernizr has to execute before page rendering. I am not sure how crucial it is and if there would be an option to load asynchronously?

**Comment by occupant** [comment]
Yes, modernizr is intentionally not async as it is used for feature detection (as opposed to device detection). It's not critical to the build (and should probably be put into the theme options so you can exclude if you like).

The file is minified already - compression will be done on your server typically (via gzip).

I'll add the optional loading as a feature request.

Cheers.

**Comment by occupant** [comment]
BTW, if you want to exclude it for now, you can remove line 70 in the html.tpl.php file.

**Comment by occupant** [comment]
Ability to disable modernizr is in the theme settings, so I'm closing this.

**Comment by joelpittet** [comment]
Just a note it’s in d8 and you can remove it but there is a couple core dependencies that need to be fixed before I can get it out of there
