### ISSUE TITLE
enhancements for https ssl sites

### ISSUE THREAD

**Issue by susielinubc** [ubc-web-services/Megatron#29]
For websites that are secured by a SSL certificate, browsers complain about the header search form 

"Mixed Content: The page at 'https://xxxx.ubc.ca/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://www.ubc.ca/search/refine/'. This endpoint should be made available over a secure connection."

**Comment by occupant** [comment]
Hmm, I don't see this. The markup megatron is generating in the latest versions is protocol agnostic (it points to //www.ubc.ca/search/refine). Are you using the default search (as opposed to the search block)?

**Comment by seanshang** [comment]
I'm the one report this to Susie. This happened with version 7.0.2. I haven't tested this with 7.0.4 yet. Will update you soon.

**Comment by seanshang** [comment]
changed the line in sites/all/themes/ubc_clf_drupal_template_7.0.2/includes/template-ubc-clf-elements.inc from http://www.ubc.ca/search/refine to https://www.ubc.ca/search/refine/ and fixed the problem.

**Comment by jelo77** [comment]
As mentioned earlier in the comments you should change it to //www.ubc.ca/search/refine (protocol-relative URL) which is how it is implemented in 7.0.4.
