### ISSUE TITLE
Menu question

### ISSUE THREAD

**Issue by reinette** [ubc-web-services/Megatron#3]
The theme seems heavily integrated to use Drupal's primary menu system. Basically the first thing I do on a new site is turn those off ;) We're using Menu Block with Menu Minipanels because we need more flexibility in our main menu than simply a list of links. Are there plans to make the theme more menu-agnostic for different uses? (I realize it's a long shot  ;)

**Comment by thiubc** [comment]
Hi James,
I do not want to hijack Renee's post but I also have a question about UBC theme menu. I hope it is OK.

How do you enable second navigation menu... like the one in http://clf.ubc.ca/implementing-the-clf/#secondary-navigation? Is it in UBC Drupal theme setting?

Thanks,
Thi

PS. I used your latest Megatron theme.

**Comment by ubcitws** [comment]
Hi Thi, 

Which department are you from and what's the website that currently uses CLF?

Susie

**Comment by thiubc** [comment]
Hi Susie,

> Which department are you from and what's the website that currently uses
> CLF?
I am from department of Mathematics. We are on progress of re-build our 
department web site (www.math.ubc.ca) so i put up a demo site 
(webdev.math.ubc.ca) with UBC theme (primary + second navigation menu) 
for our web committee to comment.
I try to enable second menu (side menu) but i am unable to get it work. 
I am using "menu block" module at this moment but i wish to keep number 
of Drupal modules low and try to use UBC theme with look and feel as 
close as possible.

Thanks,
Thi

**Comment by occupant** [comment]
Hi Thi,

For the menu block module, you can adjust the wrappers of the individual menu block with a function placed into the template.php file.

For example, assuming you're using Megatron and not a child theme of megatron (such as https://github.com/ubc-web-services/clf):

`function megatron_menu_tree__menu_block__1($variables){
  return '<div class="scrollnav" role="navigation"><ul class="nav nav-list bootstrap-sidenav">' . $variables['tree'] . '</ul></div>';
}`

This, placed at the bottom of the template.php will override menu block 1. You can confirm which menu block you're trying to adjust by going to the blocks page and clicking on the 'configure' link. The url of the configuration page will show you which block number the current block is. (ie. https://yoursite.ubc.ca/admin/structure/block/manage/menu_block/**1**/configure )

Thanks
James

**Comment by thiubc** [comment]
Thanks... James.

I will play around with it.

Best,
Thi
