### ISSUE TITLE
Copyright label in UBC footer

### ISSUE THREAD

**Issue by jelo77** [ubc-web-services/Megatron#30]
Current UBC version reads "UBC Copyright" whereas Megatron reads "Copyright"

**Comment by occupant** [comment]
Hmm, looks like this has been addressed in the current version. Closing for the time being.

**Comment by jelo77** [comment]
Well, I can see it being correct in the repository. Thought I was using the latest files based on version number. Are you pushing changes in Megatron without updating version? My version 2.4 did not have it...

**Comment by occupant** [comment]
Apologies, you're right, I had forgotten to do that. 

To make matters a little clearer moving forward, I've created a release - version 3 to remain consistent with previous versions, although there's not much difference with the latest 2.x versions.

Version 4 is also forthcoming with better child theme support and, hopefully, colour module integration. It has fairly significant structural changes, so it actually deserves a new version.
