### ISSUE TITLE
Issue in template.php

### ISSUE THREAD

**Issue by occupant** [ubc-web-services/Megatron#33]
function megatron_preprocess_html(&$vars) {
 ...

// add a body class that reflects content placement
      $vars['classes_array'][] = drupal_html_class('section-' . megatron_id_safe($section));
      $vars['classes_array'][] = drupal_html_class('path-' . megatron_id_safe($path));

These can pick ip the string 'span' due to bootstrap css and apply the bootstrap span styles to the body, breaking the layouts. Need to fix

**Comment by joelpittet** [comment]
How can they get span classes? they have prefixes of `section-` and `path-`

**Comment by occupant** [comment]
It's a problem is the path (or section name) has the string 'span' within it. So 'spanish' or 'wingspans'. The CLF (bootstrap 2.x) uses the * selector for this string to apply the span layout classes. For example:
.row-fluid [class*="span"]

This has a series of layout styles attached to it that get applied to the body in this case. The result is pretty ugly. I don't think there's a good way out short of removing the classes altogether (which aren't critical in any way to the CLF - I just added them to assist themers).

**Comment by jelo77** [comment]
I vote for removal of at least the path class
$vars['classes_array'][] = drupal_html_class('path-' . megatron_id_safe($path));

**Comment by joelpittet** [comment]
Maybe we can let people choose to turn them off/on through theme settings, and if they are on, let them know of the `span` bug caused by bootstrap 2.x?

**Comment by occupant** [comment]
I'd like to remove them as well, but I've been hesitant to do it in case it breaks someone's site. I like Joel's suggestion, but it should default to enabled so that we retain current functionality.

**Comment by joelpittet** [comment]
I've pushed a possible solution into the develop branch. 
5f549b0

**Comment by occupant** [comment]
Thanks Joel! Closing the issue.
