### ISSUE TITLE
Port to Drupal 8?

### ISSUE THREAD

**Issue by Shaun-Dychko** [ubc-web-services/Megatron#34]
Hello, does UBC Web Services have a timeline for the Drupal 8 release of the megatron theme? Is a Drupal 8 version on the roadmap?

**Comment by ubcitws** [comment]
That's in the works. You want to contact James O'Toole on our team or we can ping you when it's released on github.

Kind regards,
--
Susie Lin
Web Services

**Comment by Shaun-Dychko** [comment]
Super, thanks for getting back Susie.
